# Generated by Django 3.1.7 on 2021-04-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sender_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
